// src/components/post-comment.vue
<script setup lang="ts">
import GiscusComponent from '@giscus/vue'

const { locale } = useLocale()

defineProps<{
  frontmatter: FrontMatter
}>()
</script>

<template>
  <giscus-component
    host="https://giscus.app"
    :repo="site.giscus.repo"
    :repo-id="site.giscus.repoId"
    :category="site.giscus.category"
    :category-id="site.giscus.categoryId"
    strict="1"
    reactions-enabled="1"
    emit-metadata="1"
    input-position="bottom"
    mapping="specific"
    loading="lazy"
    :term="frontmatter.term"
    :theme="isDark ? 'dark' : 'light'"
    :lang="locale"
  />
</template>

// src/components/PostComment.tsx
import Giscus from '@giscus/solid'
import { useStore } from '@nanostores/solid'

import { site } from '~/lib/consts'
import { $theme } from '~/stores/theme'

export function PostComment() {
  const theme = useStore($theme)

  return (
    <Giscus
      repo={site.giscus.repo}
      repoId={site.giscus.repoId}
      category={site.giscus.category}
      categoryId={site.giscus.categoryId}
      strict="1"
      reactions-enabled="1"
      emit-metadata="1"
      input-position="bottom"
      theme={theme()}
      mapping="pathname"
    />
  )
}
